#!/bin/bash
# // Menjalankan Pungsi Dengan Crontab

# // Backup Setiap 60 Menit
echo "*/60 * * * *  root /usr/local/sbin/backupauto" >>/etc/crontab
echo "*/60 * * * *  root /usr/local/sbin/backup" >>/etc/crontab
echo "*/60 * * * *  root /usr/local/sbin/autobackup" >>/etc/crontab
echo "*/60 * * * *  root /usr/local/sbin/mbot" >>/etc/crontab
# // Jalankan pungsi Limit-ssh setiap 1 menit
echo "*/1 * * * *  root /luna/run/limit-ssh" >>/etc/crontab
# // Jalankan Pungsi Limit-xray setiap 1 menit
echo "*/1 * * * *  root /luna/run/limit-xray" >>/etc/crontab
# // Jalankan Pungsi Limit Quota Setiap 1 Menit
echo "*/1 * * * *  root /luna/run/limit-quota" >>/etc/crontab
# // Delete Account Trial Yang Sudah Expired Setiap 30 Menit
echo "*/30 * * * *  root /usr/local/sbin/xp" >>/etc/crontab

# // Menjalankan pungsu Dengan Cron.d
# // Backup Setiap 60 Menit
echo "*/30 * * * *  root /usr/local/sbin/autobackup" >>/etc/cron.d
echo "*/60 * * * *  root /usr/local/sbin/backupauto" >>/etc/cron.d
echo "*/60 * * * *  root /usr/local/sbin/backup" >>/etc/cron.d
echo "*/60 * * * *  root /usr/local/sbin/mbot" >>/etc/cron.d
# // Jalankan pungsi Limit-ssh setiap 1 menit
echo "*/1 * * * *  root /luna/run/limit-ssh" >>/etc/cron.d
# // Jalankan Pungsi Limit-xray setiap 1 menit
echo "*/1 * * * *  root /luna/run/limit-xray" >>/etc/cron.d
# // Jalankan Pungsi Limit Quota Setiap 1 Menit
echo "*/1 * * * *  root /luna/run/limit-quota" >>/etc/cron.d
# // Delete Account Trial Yang Sudah Expired Setiap 30 Menit
echo "*/30 * * * *  root /usr/local/sbin/xp" >>/etc/cron.d

systemctl daemon-reload
systemctl restart cron

clear
echo -e "\e[93;1mIzinkan Service \e[0m"
# // Mengizinkan Service
systemctl enable xray
systemctl enable nginx
systemctl enable udp-mini
systemctl enable limit-xray
systemctl enable limit-ssh
systemctl enable limit-quota
systemctl enable limit
systemctl enable cron
systemctl enable noobzvpns
systemctl enable vmip
systemctl enable vlip
systemctl enable trip
systemctl enable ssip
systemctl enable vme
systemctl enable vle
systemctl enable tro
systemctl enable ssr

clear
echo -e "\e[93;1mJalankan Service \e[0m"
# // Menjalankan Service
systemctl restart xray
systemctl restart nginx
systemctl restart limit
systemctl restart limit-xray
systemctl restart limit-ssh
systemctl restart limit-quota
systemctl restart udp-mini
systemctl restart cron
systemctl restart noobzvpns
systemctl restart vmip
systemctl restart vlip
systemctl restart trip
systemctl restart ssip
systemctl restart vme
systemctl restart vle
systemctl restart tro
systemctl restart ssr

clear
cd