#!/bin/bash
clear
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear

######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/lunatixmyscript/lunaip/main/ip | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/lunatixmyscript/lunaip/main/ip | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
#certifacate=$(((d1 - d2) / 86400))
clear
######################################

# \\ Vless account //
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
# \\ Trojan account //
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2
# \\ Noobzvpns Account //
et ssa=$ssx/2

nob=$(noobzvpns --info-all-user | grep -i "username" | wc -l)
noob=$(cat /etc/noobzvpns/.noobzvpns.db | grep "#nob#" | wc -l)


# // color validity
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'




function Lunatic_Banner() {
clear
echo -e "\e[38;5;162m  ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[38;5;162m  │\e[0m \033[44;1;97;1m              LUNATIC TUNNELING             \033[0m \e[38;5;162m│\e[0m"
echo -e "\e[38;5;162m  └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m "
}


function Service_System_Operating() {
echo -e "\e[38;5;162m       ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[38;5;162m       │\e[38;5;196m SYSTEM : \e[31m$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m RAM : \e[31m$(free -m | awk 'NR==2 {print $2}') MB   \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m UPTIME : \e[31m$(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m IPVPS : \e[31m$(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m ISP : \e[31m$(cat /etc/xray/isp)    \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m DOMAIN : \e[31m$(cat /etc/xray/domain)    \033[0m "
echo -e "\e[38;5;162m       └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m "
echo -e "\e[38;5;162m            ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[38;5;162m            │\e[37;1m ID :\e[92;1m $(cat /usr/bin/user)"
echo -e "\e[38;5;162m            │\e[37;1m Exp.Sc :\e[92;1m $(((d1 - d2) / 86400)).Turn\e[0m"
echo -e "\e[38;5;162m            │\e[37;1m Sc.Version :\e[92;1m 4.4.4 Lt.\e[0m"
echo -e "\e[38;5;162m            └━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m"
}

function List_Account() {
echo -e "\e[38;5;162m             \e[0;35mSSH : $ssh1 VLESS : $vla VMESS : $vma \e[0m"
echo -e "\e[38;5;162m             \e[0;36mTRO : $trb NOOBZ : $noob SDWSK : $ssa \e[0m"
}

function Acces_Use_Command() {
echo -e "\e[38;5;162m  ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[33;1m             acces use\033[0m \033[93;1m☞\033[0m \033[92;1mmenu\033[0m \e[33;1m command \033[0m " 
echo -e "\e[38;5;162m  └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m "
}



Lunatic_Banner
Service_System_Operating
List_Account
Acces_Use_Command
